# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: IFOKNR.FastbootStudio
PackageVersion: 2.3.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: FastbootStudio.exe
  PortableCommandAlias: fastbootstudio
ArchiveBinariesDependOnPath: true
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ifoknr/FastbootStudio/releases/download/v2.3.0/FastbootStudio-v2.3.0-win-x64.zip
  InstallerSha256: 06722CE373B9F978337EAA32D34BA595E3198A2019DA505C57FB6513943FB369
ManifestType: installer
ManifestVersion: 1.6.0
